name: Triển khai website tĩnh lên S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v3

      - name: Cấu hình AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Đồng bộ hóa với S3
        run: aws s3 sync ./ aws:s3:::phap-test-cicd --delete --exclude ".git/*" --exclude ".github/*"
